"""Added tags field to Photo model

Revision ID: 3210c62a2ad9
Revises: 033ec44f881b
Create Date: 2025-02-16 16:51:16.217029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3210c62a2ad9'
down_revision = '033ec44f881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('alt_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('alt_text',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
